### ISSUE TITLE
Not picking up spark.es.nodes config - always uses localhost

### ISSUE THREAD

**Issue by dkincaid** [TargetHolding/pyspark-elastic#14]
Using Spark 1.6, Python 2.7, Pyspark-elastic 0.4.2 from pyspark shell (running inside Jupyter worksheet) and it always tries to use `localhost:9200` for the Elasticsearch node when I use `rdd.saveToEs()`. Here is my command line for launching pyspark:

```
/usr/bin/pyspark --packages TargetHolding/pyspark-elastic:0.4.2 --conf spark.es.nodes=172.22.7.17 --conf spark.es.nodes.discovery=false --master yarn-client
```

and here is the error I get in the log when trying to write to ES using `rdd.saveToEs()`. As you can see it's trying to use `localhost:9200` for the ES host.

```
16/06/28 19:06:18 WARN TaskSetManager: Lost task 0.0 in stage 2.0 (TID 3, ip-172-22-2-162.vet2pet.idexxi.com): org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)
- all nodes failed; tried [[localhost:9200]] 
    at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
    at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:383)
    at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:363)
    at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:367)
    at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:121)
    at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:513)
    at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:177)
    at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:378)
    at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
    at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
    at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by aeneaswiener** [comment]
I am seeing the same behaviour. Did you figure out a fix for this @dkincaid?

**Comment by soufiane-fadil** [comment]
i have the same issue ? no update since that day ?

**Comment by dkincaid** [comment]
Sorry, @aeneaswiener, just saw your question. The only way I could find to work around this was to specify the node in the `saveToEs()` function. Something like this:

```python
import pyspark_elastic
esrdd.saveToEs("result", nodes="172.17.22.3", mapping_id="id")
```
