### ISSUE TITLE
net.razorvine.pickle.PickleException during rdd.saveToEs()

### ISSUE THREAD

**Issue by dkincaid** [TargetHolding/pyspark-elastic#15]
When writing data from an RDD to Elasticsearch using rdd.saveToEs() I occasionally get a `net.razorvine.pickle.PickleException:` error and once enough of them happen the job fails. I haven't been able to find a specific point in the loading when it is happening. There doesn't seem to be a pattern to it. Sometimes I can get only 5 million records indexed and sometimes I can get 20 million.

My index mapping does have nested and object types in it.

Spark 1.6.1, Python 2.7

Here is the stack trace:

```
16/06/29 03:04:07 WARN TaskSetManager: Lost task 19.1 in stage 2.0 (TID 45, ip-172-22-2-195.vet2pet.idexxi.com): net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
    at net.razorvine.pickle.Pickler.put_javabean(Pickler.java:705)
    at net.razorvine.pickle.Pickler.dispatch(Pickler.java:323)
    at net.razorvine.pickle.Pickler.save(Pickler.java:137)
    at net.razorvine.pickle.Pickler.put_arrayOfObjects(Pickler.java:493)
    at net.razorvine.pickle.Pickler.dispatch(Pickler.java:205)
    at net.razorvine.pickle.Pickler.save(Pickler.java:137)
    at net.razorvine.pickle.Pickler.dump(Pickler.java:107)
    at net.razorvine.pickle.Pickler.dumps(Pickler.java:92)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:121)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:110)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:110)
    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:452)
    at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:280)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1765)
    at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:239)
```

**Comment by domkck** [comment]
Hi, I'm seeing the same error, also seemingly without a pattern. Here's my stack trace:

```
Py4JJavaError: An error occurred while calling o60.saveJsonToEs.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 1.0 failed 4 times, most recent failure: Lost task 7.3 in stage 1.0 (TID 28, ip-11-0-3-170.eu-west-1.compute.internal): net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
    at net.razorvine.pickle.Pickler.put_javabean(Pickler.java:705)
    at net.razorvine.pickle.Pickler.dispatch(Pickler.java:323)
    at net.razorvine.pickle.Pickler.save(Pickler.java:137)
    at net.razorvine.pickle.Pickler.put_arrayOfObjects(Pickler.java:493)
    at net.razorvine.pickle.Pickler.dispatch(Pickler.java:205)
    at net.razorvine.pickle.Pickler.save(Pickler.java:137)
    at net.razorvine.pickle.Pickler.dump(Pickler.java:107)
    at net.razorvine.pickle.Pickler.dumps(Pickler.java:92)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:121)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.next(SerDeUtil.scala:110)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at org.apache.spark.api.python.SerDeUtil$AutoBatchedPickler.foreach(SerDeUtil.scala:110)
    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:452)
    at org.apache.spark.api.python.PythonRunner$WriterThread$$anonfun$run$3.apply(PythonRDD.scala:280)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1765)
    at org.apache.spark.api.python.PythonRunner$WriterThread.run(PythonRDD.scala:239)

Driver stacktrace:
    at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
    at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
    at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
    at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
    at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1922)
    at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:67)
    at org.elasticsearch.spark.rdd.EsSpark$.saveJsonToEs(EsSpark.scala:95)
    at org.elasticsearch.spark.package$SparkJsonRDDFunctions.saveJsonToEs(package.scala:46)
    at pyspark_elastic.PythonHelper.saveJsonToEs(PythonHelper.scala:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
    at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
    at py4j.Gateway.invoke(Gateway.java:259)
    at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
    at py4j.commands.CallCommand.execute(CallCommand.java:79)
    at py4j.GatewayConnection.run(GatewayConnection.java:209)
    at java.lang.Thread.run(Thread.java:745)
Caused ...
  File "review/apps/batch/sink.py", line 22, in sink
    sink_tweets_to_elasticsearch(sql_context, input_dir)
  File "review/apps/batch/sink.py", line 31, in sink_tweets_to_elasticsearch
    .saveToEs(tweet_index_name + "/tweet", mapping_id="tweet_id", **es_conf)
  File "pyspark_elastic/rdd.py", line 60, in saveToEs
    saveJsonToEs(rdd.map(json.dumps), resource_write=resource_write, **kwargs)
  File "pyspark_elastic/rdd.py", line 65, in saveJsonToEs
    helper(rdd.ctx).saveJsonToEs(rdd._jrdd, kwargs)
  File "py4j/java_gateway.py", line 813, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "pyspark/sql/utils.py", line 45, in deco
    return f(*a, **kw)
  File "py4j/protocol.py", line 308, in get_return_value
    format(target_id, ".", name), value)
```
